"""Catalogo de perfiles de sitios y juegos para control parental web."""


SITE_BLOCKING_PROFILES = (
    {
        "id": "youtube",
        "name": "YouTube",
        "short": "YT",
        "category": "Video",
        "description": "Bloqueo YouTube",
        "theme": "youtube",
        "icon": "assets/icons/youtube.svg",
        "domains": (
            "youtube",
            "youtube.com",
            "www.youtube.com",
            "m.youtube.com",
            "youtu.be",
            "googlevideo",
            "googlevideo.com",
            "ytimg",
            "ytimg.com",
            "s.ytimg.com",
            "youtubei.googleapis.com",
            "youtube.googleapis.com",
            "youtube-nocookie.com",
            "www.youtube-nocookie.com",
        ),
    },
    {
        "id": "facebook",
        "name": "Facebook",
        "short": "f",
        "category": "Social",
        "description": "Bloqueo Facebook",
        "theme": "facebook",
        "icon": "assets/icons/facebook.svg",
        "domains": (
            "facebook",
            "facebook.com",
            "www.facebook.com",
            "m.facebook.com",
            "mbasic.facebook.com",
            "graph.facebook.com",
            "graph-video.facebook.com",
            "connect.facebook.net",
            "facebook.net",
            "fb.com",
            "fbcdn",
            "fbcdn.net",
            "xx.fbcdn.net",
            "static.xx.fbcdn.net",
            "scontent.xx.fbcdn.net",
            "video.xx.fbcdn.net",
            "fbsbx",
            "fbsbx.com",
            "messenger",
            "messenger.com",
            "m.me",
            "meta.com",
        ),
    },
    {
        "id": "instagram",
        "name": "Instagram",
        "short": "IG",
        "category": "Social",
        "description": "Bloqueo Instagram",
        "theme": "instagram",
        "icon": "assets/icons/instagram.svg",
        "domains": (
            "instagram",
            "instagram.com",
            "www.instagram.com",
            "m.instagram.com",
            "i.instagram.com",
            "api.instagram.com",
            "graph.instagram.com",
            "cdninstagram.com",
            "scontent.cdninstagram.com",
            "ig.me",
        ),
    },
    {
        "id": "tiktok",
        "name": "TikTok",
        "short": "TT",
        "category": "Social",
        "description": "Bloqueo TikTok",
        "theme": "tiktok",
        "icon": "assets/icons/tiktok.svg",
        "domains": (
            "tiktok",
            "tiktok.com",
            "www.tiktok.com",
            "m.tiktok.com",
            "vm.tiktok.com",
            "vt.tiktok.com",
            "tiktokcdn.com",
            "tiktokv.com",
            "musical.ly",
            "byteoversea.com",
            "ibytedtos.com",
        ),
    },
    {
        "id": "x-twitter",
        "name": "X",
        "short": "X",
        "category": "Social",
        "description": "Bloqueo X",
        "theme": "x",
        "icon": "assets/icons/x.svg",
        "domains": (
            "x.com",
            "www.x.com",
            "twitter.com",
            "www.twitter.com",
            "mobile.twitter.com",
            "api.twitter.com",
            "t.co",
            "twimg.com",
            "pbs.twimg.com",
            "video.twimg.com",
            "abs.twimg.com",
        ),
    },
    {
        "id": "threads",
        "name": "Threads",
        "short": "TH",
        "category": "Social",
        "description": "Bloqueo Threads",
        "theme": "threads",
        "icon": "assets/icons/threads.webp",
        "domains": (
            "threads",
            "threads.net",
            "www.threads.net",
            "threads.com",
            "www.threads.com",
            "threads.instagram.com",
        ),
    },
    {
        "id": "reddit",
        "name": "Reddit",
        "short": "R",
        "category": "Social",
        "description": "Bloqueo Reddit",
        "theme": "reddit",
        "icon": "assets/icons/reddit.svg",
        "domains": (
            "reddit",
            "reddit.com",
            "www.reddit.com",
            "old.reddit.com",
            "new.reddit.com",
            "redd.it",
            "redditmedia.com",
            "redditstatic.com",
            "reddituploads.com",
            "redditinc.com",
        ),
    },
    {
        "id": "free-fire",
        "name": "Free Fire",
        "short": "FF",
        "category": "Juego",
        "description": "Bloqueo Free Fire",
        "theme": "freefire",
        "icon": "assets/icons/free-fire.svg",
        "domains": (
            "freefire",
            "freefiremobile.com",
            "ff.garena.com",
            "garena",
            "garena.com",
            "garenanow.com",
            "garenanow.com.br",
        ),
    },
    {
        "id": "roblox",
        "name": "Roblox",
        "short": "RB",
        "category": "Juego",
        "description": "Bloqueo Roblox",
        "theme": "roblox",
        "icon": "assets/icons/roblox.webp",
        "domains": (
            "roblox",
            "roblox.com",
            "www.roblox.com",
            "api.roblox.com",
            "auth.roblox.com",
            "games.roblox.com",
            "assetdelivery.roblox.com",
            "rbxcdn.com",
            "robloxcdn.com",
        ),
    },
    {
        "id": "ea-fc-mobile",
        "name": "EA FC Mobile",
        "short": "FC",
        "category": "Juego",
        "description": "Bloqueo EA FC Mobile",
        "theme": "eafc",
        "icon": "assets/icons/ea-fc-mobile.webp",
        "domains": (
            "easports",
            "easports.com",
            "ea.com",
            "fcmobile.ea.com",
            "eaassets-a.akamaihd.net",
            "eafootballmobile.com",
        ),
    },
    {
        "id": "clash-royale",
        "name": "Clash Royale",
        "short": "CR",
        "category": "Juego",
        "description": "Bloqueo Clash Royale",
        "theme": "clashroyale",
        "icon": "assets/icons/clash-royale.svg",
        "domains": (
            "clashroyale",
            "clashroyale.com",
            "clash.com",
            "supercell",
            "supercell.com",
            "supercellid.com",
            "supercellgames.com",
        ),
    },
    {
        "id": "clash-of-clans",
        "name": "Clash of Clans",
        "short": "COC",
        "category": "Juego",
        "description": "Bloqueo Clash of Clans",
        "theme": "clashclans",
        "icon": "assets/icons/clash-of-clans.svg",
        "domains": (
            "clashofclans",
            "clashofclans.com",
            "supercell",
            "supercell.com",
            "supercellid.com",
            "supercellgames.com",
        ),
    },
    {
        "id": "brawl-stars",
        "name": "Brawl Stars",
        "short": "BS",
        "category": "Juego",
        "description": "Bloqueo Brawl Stars",
        "theme": "brawlstars",
        "icon": "assets/icons/brawl-stars.svg",
        "domains": (
            "brawlstars",
            "brawlstars.com",
            "supercell",
            "supercell.com",
            "supercellid.com",
            "supercellgames.com",
        ),
    },
    {
        "id": "call-of-duty-mobile",
        "name": "Call of Duty Mobile",
        "short": "COD",
        "category": "Juego",
        "description": "Bloqueo Call of Duty Mobile",
        "theme": "codmobile",
        "icon": "assets/icons/call-of-duty-mobile.svg",
        "domains": (
            "callofduty",
            "callofduty.com",
            "www.callofduty.com",
            "activision.com",
            "www.activision.com",
            "codm",
            "codmobile",
            "demonware.net",
        ),
    },
    {
        "id": "pubg-mobile",
        "name": "PUBG Mobile",
        "short": "PUBG",
        "category": "Juego",
        "description": "Bloqueo PUBG Mobile",
        "theme": "pubg",
        "icon": "assets/icons/pubg-mobile.svg",
        "domains": (
            "pubgmobile",
            "pubgmobile.com",
            "www.pubgmobile.com",
            "pubg.com",
            "krafton.com",
            "tencentgames.com",
        ),
    },
)

PARENTAL_HARDENING_RULES = (
    {
        "descripcion": "Bloqueo QUIC 443",
        "url": "",
        "puerto_inicio": "443",
        "puerto_fin": "443",
        "protocolo": "UDP",
    },
    {
        "descripcion": "Bloqueo QUIC 80",
        "url": "",
        "puerto_inicio": "80",
        "puerto_fin": "80",
        "protocolo": "UDP",
    },
    {
        "descripcion": "Bloqueo DNS privado",
        "url": "",
        "puerto_inicio": "853",
        "puerto_fin": "853",
        "protocolo": "BOTH",
    },
    {
        "descripcion": "Bloqueo Apple Relay",
        "url": "mask.icloud.com",
        "puerto_inicio": "0",
        "puerto_fin": "0",
        "protocolo": "BOTH",
    },
    {
        "descripcion": "Bloqueo Apple Relay",
        "url": "mask-h2.icloud.com",
        "puerto_inicio": "0",
        "puerto_fin": "0",
        "protocolo": "BOTH",
    },
    {
        "descripcion": "Bloqueo DoH Google",
        "url": "dns.google",
        "puerto_inicio": "0",
        "puerto_fin": "0",
        "protocolo": "BOTH",
    },
)


def get_site_blocking_profile(profile_id):
    """Devuelve un perfil de bloqueo por identificador."""

    for profile in SITE_BLOCKING_PROFILES:
        if profile["id"] == profile_id:
            return profile

    raise ValueError("El perfil de bloqueo no existe.")
